import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

/**
 * Create a pull request via gh CLI.
 */
export async function createPullRequest({ repo, branch, baseBranch, parsed, changedFiles }) {
  const title = `[Sentry Autofix] ${truncate(parsed.title, 60)}`;

  const body = buildPrBody(parsed, changedFiles);

  const { stdout } = await execFileAsync(
    "gh",
    [
      "pr",
      "create",
      "--repo",
      repo,
      "--base",
      baseBranch,
      "--head",
      branch,
      "--title",
      title,
      "--body",
      body,
      "--label",
      "sentry-autofix",
    ],
    { timeout: 30_000 }
  );

  const prUrl = stdout.trim();
  console.log(`[github] PR created: ${prUrl}`);
  return prUrl;
}

/**
 * Ensure the "sentry-autofix" label exists on the repo.
 */
export async function ensureLabel(repo) {
  try {
    await execFileAsync(
      "gh",
      ["label", "create", "sentry-autofix", "--repo", repo, "--color", "D93F0B", "--description", "Automated fix from Sentry error"],
      { timeout: 10_000 }
    );
  } catch {
    // Label already exists, that's fine
  }
}

function buildPrBody(parsed, changedFiles) {
  let body = `## Sentry Autofix\n\n`;
  body += `This PR was automatically generated to fix a production error detected by Sentry.\n\n`;

  body += `### Error Details\n\n`;
  body += `| Field | Value |\n|-------|-------|\n`;
  body += `| **Title** | ${parsed.title} |\n`;
  body += `| **Level** | ${parsed.level} |\n`;
  body += `| **Platform** | ${parsed.platform || "N/A"} |\n`;

  if (parsed.culprit) {
    body += `| **Culprit** | \`${parsed.culprit}\` |\n`;
  }

  if (parsed.webUrl || parsed.issueUrl) {
    body += `| **Sentry Issue** | ${parsed.webUrl || parsed.issueUrl} |\n`;
  }

  if (parsed.triggeredRule) {
    body += `| **Alert Rule** | ${parsed.triggeredRule} |\n`;
  }

  if (parsed.stacktrace) {
    body += `\n### Stack Trace\n\n\`\`\`\n`;
    for (const ex of parsed.stacktrace) {
      body += `${ex.type}: ${ex.value}\n`;
      const appFrames = ex.frames.filter((f) => f.inApp);
      const frames = appFrames.length > 0 ? appFrames : ex.frames.slice(-10);
      for (const frame of frames) {
        body += `  at ${frame.function || "?"} (${frame.filename}:${frame.lineNo})\n`;
      }
    }
    body += `\`\`\`\n`;
  }

  body += `\n### Files Changed\n\n`;
  for (const file of changedFiles) {
    body += `- \`${file}\`\n`;
  }

  body += `\n---\n`;
  body += `*Generated by [sentry-autofix](https://github.com) using Claude Code*\n`;

  return body;
}

function truncate(str, max) {
  return str.length > max ? str.slice(0, max - 3) + "..." : str;
}
